config/routes.rb
AlumniApp::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :photos do
    member do
      get 'download'
    end
  end

  resources :notes do
    resources :comments
    member do
      get 'download'
    end
  end

  resources :users  do
    collection do
      get 'login'
      post 'login'
      get 'signup'
      post 'signup'

      get 'logout'

    end

    member do
    end
  end  

  resources :messages do
    resources :comments
  end

  resources :events do
    resources :comments
    resources :tasks
    member do
      post 'rsvp' 
      post 'remove_rsvp' 
    end
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :body, :title, :user_id

  belongs_to :user
  has_many :comments, :as => :commentable

  validates :title, :presence => true
  validates :body, :presence => true

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_filter :check_logged_in, :only => [:create, :new, :edit, :update, :destroy]

  before_filter :get_message_object, :only => [:show, :edit, :update, :destroy]

  before_filter :check_owner, :only => [:edit, :update, :destroy]

  private

  def get_message_object
    if params[:commit] == "Cancel"
      redirect_to messages_path and return
    end

    @message = Message.find_by_id(params[:id])
    if @message.nil?
      flash[:error] = "Sorry, No message was found!"
      redirect_to messages_path
    end    
  end

  def check_owner
    if @message.user!=current_user
      flash[:error] = "Sorry, You are not a valid user"
      redirect_to messages_path
    end
  end
  
  public

  def index
    @messages = Message.all
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    @message.user = current_user
    if @message.save
      flash[:notice] = "Message has been successfully created"
      redirect_to messages_path
    else
      render :action => :new
    end
  end

  def show
    @commentable = @message
    @comments = @commentable.comments
    @comment = Comment.new
  end

  def edit
  end

  def update
    if @message.update_attributes(params[:message])
      flash[:notice] = "Message has been successfully updated."
      redirect_to message_path(@message)
    else
      render :action => :edit
    end
  end

  def destroy
    @message.destroy
    flash[:notice] = "Message has been deleted."
    redirect_to messages_path
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%
  if @message.new_record?
    url = messages_path
    method = :post
  else
    url = message_path(@message)
    method = :put
  end
%>

  <% if @message.errors.any?%>
    <div id="errors" style="color:red;padding:10px; border:2px solid yellow; background-color: lightyellow;">
      <strong>Message was not saved because of the following errors:</strong>
      <ul>
        <% @message.errors.full_messages.each do |message|%>
          <li><%= message%></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<div style="padding:10px; margin:10px;background-color:#efefef; border: 2px solid #aaa">
  <%= form_for @message, :url => url, :method => method do |f|%>

    Title: <%= f.text_field :title %> <br/><br/>

    Body: <%= f.text_area :body %> <br/><br/>

    <%= f.submit "Save this Message" %>

    <%= f.submit "Cancel" %>
  <% end %>
</div>

app/views/messages/edit.html.erb
<%= link_to "View All Messages", messages_path%>
<br/>
<h3>Edit Message</h3>
<br/>
<hr/>
<%= render :partial => "form"%>

app/views/messages/index.html.erb
<% if logged_in? %>
  <%= link_to "Create New Message", new_message_path%>
<% else %>
  <%= link_to "Login", login_users_path%> and add new messages.
<% end %>
<br/>
<hr/>
 <% @messages.each do |message|%>
   <div style="padding:10px; margin:10px;background-color:#efefef; border: 2px solid #aaa">
     <strong><%= link_to message.title, message_path(message)%></strong>
     <br/>

      Title: <%= message.title%>
      <br/>

      <small>Published on: <%= format_date(message.created_at)%></small>
      <br/>

      <small>Published by: <%= message.user.name %></small>
      <br/>

    </div>
  <% end %>

app/views/messages/new.html.erb
<%= link_to "View All Messages", messages_path%>
<br/>
<h3>Create New Message</h3>
<br/>
<hr/>
<%= render :partial => "form"%>

app/views/messages/show.html.erb
<%= link_to "View All Messages", messages_path%>
<br/>
<hr/>
<div style="padding:10px; margin:10px;background-color:#efefef; border: 2px solid #aaa">
  <strong><%= @message.title %></strong>
  <br/>

  <%= simple_format(@message.body) %>

  <small>Published on: <%= format_date(@message.created_at)%></small>
  <br/>

</div>

<% if logged_in? && @message.user==current_user%>
  <%= link_to "Edit this Message", edit_message_path(@message)%> | 
<% end %>
<% if logged_in? %>
  <%= link_to_function "Add Comment", "$('#new_comment').show()" %>
<% end %>

<h3>Comments</h3>
<%= render :partial => "comments/form"%>
<%= render :partial => "comments/comment"%>