config/routes.rb
AlumniApp::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :photos do
    member do
      get 'download'
    end
  end

  resources :notes do
    resources :comments
    member do
      get 'download'
    end
  end

  resources :users  do
    collection do
      get 'login'
      post 'login'
      get 'signup'
      post 'signup'

      get 'logout'

    end

    member do
    end
  end  

  resources :messages do
    resources :comments
  end

  resources :events do
    resources :comments
    resources :tasks
    member do
      post 'rsvp' 
      post 'remove_rsvp' 
    end
  end

end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :user_id, :file

  belongs_to :user

  has_attached_file :file,
  :path => ":rails_root/private/user_data/notes/:id/:filename"

  has_many :comments, :as => :commentable

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  before_filter :check_logged_in
  before_filter :get_file, :only => [:show, :download, :destroy]
  before_filter :check_owner, :only => [:destroy, :download]

  private

  def get_file
    @note = Note.find_by_id(params[:id])
    unless @note
      flash[:error] = "Sorry, We couldn't find the requested note"
      redirect_to notes_path
    end    
  end

  def check_owner
    if @note.user!=current_user
      flash[:error] = "Sorry, You are not a valid user"
      redirect_to notes_path
    end
  end
  
  public

  def index
    @notes = Note.all
  end

  def show
    @commentable = @note
    @comments = @commentable.comments
    @comment = Comment.new
  end

  def download
    send_file(@note.file.path, :filename => @note.file_file_name, :disposition => "note")
  end

  def new
    @note = Note.new
  end  

  def create
    @note = Note.new(params[:note])
    @note.user = current_user
    if @note.save
      flash[:notice] = "Note has been saved successfully!"
      redirect_to notes_path
    else
      render :action => :new
    end  
  end

  def destroy
    @note.destroy
    flash[:notice] = "Note has been removed successfully"
    redirect_to notes_path
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/index.html.erb
<% if logged_in? %>
  <%= link_to "Create New Note", new_note_path%>
<% else %>
  <%= link_to "Login", login_users_path%> and add new notes.
<% end %>
<br/>
<hr/>


<div style="padding:10px; margin:10px;background-color:#efefef; border: 2px solid #aaa">

<% unless @notes.empty? %>
  <ul>
    <% @notes.each do |note| %>
    <li><%= link_to note.file_file_name, note_path(note)%><br/>

    Created by: <%= note.user.name%> <br/>

    <%= link_to "Download", download_note_path(note)%>

  <%= link_to "Delete", note_path(note), :method => :delete, :data => {:confirm => "Are you sure you want to permanently delete this note?"}%>
    </li>
    <% end %>
  </ul>
<% else %>
  No Notes Found!
<% end %>

</div>

app/views/notes/new.html.erb
<h2>Add New Note</h2>

<div class="form">
  <%= form_for :note, :url=> notes_path, :html => {:multipart => true} do |f| %>
    Select Note : <%= f.file_field :file%>
    <br/>

    <%= f.submit "Upload Note"%>

  <% end %>
</div>

app/views/notes/show.html.erb
<%= link_to "View All Notes", notes_path%>
<br/>
<div class="photo">
    Note Name:<%= @note.file_file_name%>
</div>

<%= link_to "Download this Note", download_note_path(@note)%> | 

<%= link_to "Delete", note_path(@note), :method => :delete, :data => {:confirm => "Are you sure you want to permanently delete this note?"}%> | 

<% if logged_in? %>
  <%= link_to_function "Add Comment", "$('#new_comment').show()" %>
<% end %>
<br/>
<h3>Comments</h3>
<%= render :partial => "comments/form"%>
<%= render :partial => "comments/comment"%>