config/routes.rb
AlumniApp::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :photos do
    member do
      get 'download'
    end
  end

  resources :notes do
    resources :comments
    member do
      get 'download'
    end
  end

  resources :users  do
    collection do
      get 'login'
      post 'login'
      get 'signup'
      post 'signup'

      get 'logout'

    end

    member do
    end
  end  

  resources :messages do
    resources :comments
  end

  resources :events do
    resources :comments
    resources :tasks
    member do
      post 'rsvp' 
      post 'remove_rsvp' 
    end
  end

end

app/views/shared/_footer.html.erb
<div id="footer">
  <center>
    The AlumniApp. CopyRight &copy; <%= Time.now.year %>. All rights reserved.
  </center>
</div>

app/views/shared/_header.html.erb
<div id="header">
  <h2 class="title">The Alumni App</h2>
  <div id="nav">
    <%= link_to "Messages", messages_path, :class => (params[:controller]=="messages" ? "active" : "")%>
    <%= link_to "Events", events_path, :class => (params[:controller]=="events" ? "active" : "")%>

    <%= link_to "Photos", photos_path, :class => (params[:controller]=="photos" ? "active" : "")%>

    <%= link_to "Notes", notes_path, :class => (params[:controller]=="notes" ? "active" : "")%>

    <div id="login_links">
      <% if logged_in? %>
        <%= link_to "Logout", logout_users_path%>
      <% else %>
        <%= link_to "Login", login_users_path%>
        <%= link_to "SignUp", new_user_path%>
      <% end %>
    </div>

  </div>

</div>