config/routes.rb
AlumniApp::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :photos do
    member do
      get 'download'
    end
  end

  resources :notes do
    resources :comments
    member do
      get 'download'
    end
  end

  resources :users  do
    collection do
      get 'login'
      post 'login'
      get 'signup'
      post 'signup'

      get 'logout'

    end

    member do
    end
  end  

  resources :messages do
    resources :comments
  end

  resources :events do
    resources :comments
    resources :tasks
    member do
      post 'rsvp' 
      post 'remove_rsvp' 
    end
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :description, :event_at, :title, :user_id, :event_at_date, :event_at_time

  attr_accessor :event_at_date, :event_at_time


  belongs_to :user

  has_many :comments, :as => :commentable
  has_many :photos, :dependent => :destroy
  has_many :tasks, :dependent => :destroy
  has_many :event_user_mappings, :dependent => :destroy
  has_many :users, :through => :event_user_mappings


  validates :title, :presence => true
  validates :description, :presence => true

  validates_format_of :event_at_time, :with => /\d{1,2}:\d{2}/


  after_initialize :get_datetimes
  before_validation :set_datetimes


 # add some callbacks
  after_initialize :get_datetimes # convert db format to accessors
  before_validation :set_datetimes # convert accessors back to db format

  def get_datetimes
    self.event_at ||= Time.now  # if the event_at time is not set, set it to now

    self.event_at_date ||= self.event_at.to_date.to_s(:db) # extract the date is yyyy-mm-dd format
    self.event_at_time ||= "#{'%02d' % self.event_at.hour}:#{'%02d' % self.event_at.min}" # extract the time
  end

  def set_datetimes
    self.event_at = "#{self.event_at_date} #{self.event_at_time}:00" # convert the two fields back to db
  end  


end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_filter :check_logged_in, :only => [:create, :new, :edit, :update, :destroy]

  before_filter :get_event_object, :only => [:rsvp, :remove_rsvp, :show, :edit, :update, :destroy]

  before_filter :check_owner, :only => [:edit, :update, :destroy]

  private

  def get_event_object
    if params[:commit] == "Cancel"
      redirect_to events_path and return
    end

    @event = Event.find_by_id(params[:id])
    if @event.nil?
      flash[:error] = "Sorry, No event was found!"
      redirect_to events_path
    end    
  end

  def check_owner
    if @event.users!=current_user
      flash[:error] = "Sorry, You are not a valid user"
      redirect_to events_path
    end
  end
  
  public

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
    @users = User.find(:all)
  end

  def create
    @event = Event.new(params[:event])
    @event.user = current_user
    if @event.save
      flash[:notice] = "Event has been successfully created"
      redirect_to events_path
    else
      render :action => :new
    end
  end

  def show
    @commentable = @event
    @comments = @commentable.comments
    @comment = Comment.new
    @task = Task.new
  end

  def edit
  end

  def update
    if @event.update_attributes(params[:event])
      flash[:notice] = "Event has been successfully updated."
      redirect_to event_path(@event)
    else
      flash[:error] = "Unable to save the event"
      render :action => :edit
    end
  end

  def rsvp
    if @event.users.include?(current_user)
      flash[:error] = "RSVP has already been accepted"
    else
      flash[:notice] = "RSVP has been accepted"
      @event.users << current_user
    end
    redirect_to event_path(@event)
  end

  def remove_rsvp
    if @event.users.include?(current_user)
      @event.users.delete(current_user)
      flash[:notice] = "RSVP has been successfully removed"
    else
      flash[:error] = "Sorry, you have not RSVP for the event"
    end
    redirect_to event_path(@event)
  end


end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%
  if @event.new_record?
    url = events_path
    method = :post
  else
    url = event_path(@event)
    method = :put
  end
%>

  <% if @event.errors.any?%>
    <div id="errors" style="color:red;padding:10px; border:2px solid yellow; background-color: lightyellow;">
      <strong>Event was not saved because of the following errors:</strong>
      <ul>
        <% @event.errors.full_messages.each do |message|%>
          <li><%= message%></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<div style="padding:10px; margin:10px;background-color:#efefef; border: 2px solid #aaa">
  <%= form_for @event, :url => url, :method => method do |f|%>

    Title: <%= f.text_field :title %> <br/><br/>

    Description: <%= f.text_area :description %> <br/><br/>

    <%= f.label :event_at %><br />
    <%= f.text_field :event_at_date, :class => 'datepicker', :size => 10, :maxlength => 10 %>
      <%= f.text_field :event_at_time, :size => 5, :maxlength => 5 %>
      <br/><br/>

    <%= f.submit "Save this Event" %>

    <%= f.submit "Cancel" %>
  <% end %>
</div>

app/views/events/edit.html.erb
<%= link_to "View All Events", events_path%>
<br/>
<h3>Edit Event</h3>
<br/>
<hr/>
<%= render :partial => "form"%>

app/views/events/index.html.erb
<% if logged_in? %>
  <%= link_to "Create New Event", new_event_path%>
<% else %>
  <%= link_to "Login", login_users_path%> and add new events.
<% end %>
<br/>
<hr/>

<% if @events.empty? %>
  No Events Found!!
<% else %>
 <% @events.each do |event|%>
   <div style="padding:10px; margin:10px;background-color:#efefef; border: 2px solid #aaa">
     <strong><%= link_to event.title, event_path(event)%></strong>
     <br/>

      Title: <%= event.title%>
      <br/>

      <small>Published on: <%= format_date(event.created_at)%></small>
      <br/>

      <small>Published by: <%= event.user.name %></small>
      <br/>

    </div>
  <% end %>
<% end %>

app/views/events/new.html.erb
<%= link_to "View All Events", events_path%>
<br/>
<h3>Create New Event</h3>
<br/>
<hr/>
<%= render :partial => "form"%>

app/views/events/show.html.erb
<%= link_to "View All Events", events_path%>
<br/>
<hr/>
<div style="padding:10px; margin:10px;background-color:#efefef; border: 2px solid #aaa">
  <strong><%= @event.title %></strong>
  <br/>

  <%= simple_format(@event.description) %><br/>

  <strong>Event on: <%= @event.event_at_date%> at <%= @event.event_at_time%></strong>
  <br/>

  <small>Published on: <%= format_date(@event.created_at)%></small>
  <br/>

  <small>Published by: <%= @event.user.name%></small>
  <br/>
</div>

<% if logged_in? && @event.user == current_user%>
  <%= link_to "Edit this Event", edit_event_path(@event)%> | 
  <% if @event.users.include?(current_user)%>
    <%= link_to "Remove RSVP", remove_rsvp_event_path(@event), :method => :post, :data=>{:confirm=>"Are you sure you want to remove RSVP from this event?"}%> | 
    <% else %>
  <%= link_to "RSVP", rsvp_event_path(@event), :method => :post, :data=>{:confirm=>"Are you sure, you want to RSVP for this event?"}%> |
    <% end %> 
  <%= link_to_function "Add Task",  "$('#new_task').show()" %> | 
<% end %>
<% if logged_in? %>
  <%= link_to_function "Add Comment", "$('#new_comment').show()" %>
<% end %>

<h3>Comments</h3>
<%= render :partial => "comments/form"%>
<%= render :partial => "comments/comment"%>

<h3>Tasks</h3>
<%= render :partial => "tasks/form"%>
<%= render :partial => "tasks/task"%>